package org.corporateforce.server.model;

// Generated 25.12.2014 2:00:33 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;


/**
 * Profiles generated by hbm2java
 */
@Entity
@Table(name = "profiles", catalog = "corporateforce")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})  

public class Profiles implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private boolean loginEnabled;
	private boolean systemControl;
	private boolean manageUsers;

	public Profiles() {
	}

	public Profiles(String name, boolean loginEnabled, boolean systemControl,
			boolean manageUsers) {
		this.name = name;
		this.loginEnabled = loginEnabled;
		this.systemControl = systemControl;
		this.manageUsers = manageUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "LOGIN_ENABLED", nullable = false)
	public boolean isLoginEnabled() {
		return this.loginEnabled;
	}

	public void setLoginEnabled(boolean loginEnabled) {
		this.loginEnabled = loginEnabled;
	}

	@Column(name = "SYSTEM_CONTROL", nullable = false)
	public boolean isSystemControl() {
		return this.systemControl;
	}

	public void setSystemControl(boolean systemControl) {
		this.systemControl = systemControl;
	}

	@Column(name = "MANAGE_USERS", nullable = false)
	public boolean isManageUsers() {
		return this.manageUsers;
	}

	public void setManageUsers(boolean manageUsers) {
		this.manageUsers = manageUsers;
	}

}
